tan-2023-security:
  type: article
  title: Security Verification of Low-Trust Architectures
  author:
  - Tan, Qinhan
  - Fisseha, Yonathan
  - Chen, Shibo
  - Biernacki, Lauren
  - Jeannin, Jean-Baptiste
  - Malik, Sharad
  - Austin, Todd
  date: 2023-11
  page-range: 945-959
  url: http://dx.doi.org/10.1145/3576915.3616643
  serial-number:
    doi: 10.1145/3576915.3616643
  parent:
    type: proceedings
    title: Proceedings of the 2023 ACM SIGSAC Conference on Computer and Communications Security
    publisher: ACM
    parent:
      type: proceedings
      title: CCS ’23
